[package]
name = "lunaris_emu"
version = "0.1.0"
edition = "2024"

[dependencies]
audio = { workspace = true }
free_bios = { workspace = true }
gpu = { workspace = true }
mem_const = { workspace = true }
tracing = { workspace = true, optional = true }

[features]
default = ["tracing"]
tracing = ["dep:tracing"]
