[package]
name = "gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
mem_const = { workspace = true }
tracing = { workspace = true, optional = true }

[features]
default = ["tracing"]
tracing = ["dep:tracing"]
